image: node:19-alpine

cache:
  paths:
    - node_modules/
    - dist/
    - docs/

stages:
  - .pre
  - build
  - lint
  - test
  - security
  - deploy
  # for ecs template
  - review
  - dast
  - production
  - cleanup

.resolve-bash-git-for-alpine:
  image: node:19-alpine
  before_script:
    - |
      apk add bash
      apk add git

.resolve-core:
  before_script: |
    git config --system credential.helper store
    echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com" > ~/.git-credentials
    bash scripts/init.sh

.resolve-submodule: &resolve-submodule
  before_script:
    - !reference [.resolve-bash-git-for-alpine, before_script]
    - !reference [.resolve-core, before_script]

.resolve-variables-by-env: &resolve-variables-by-env
  before_script:
    - |
      if [ $CI_COMMIT_BRANCH == "main" ]; then
        EMV=production
        CI_ENVIRONMENT_NAME=production
        APP_NAME=syncday-api
        DOCKER_FILE=Dockerfile
      elif [ $CI_COMMIT_TAG != null ]; then
        EMV=staging
        CI_ENVIRONMENT_NAME=staging
        APP_NAME=stg-syncday-api
        DOCKER_FILE=Dockerfile.stg
      else
        EMV=development
        CI_ENVIRONMENT_NAME=development
        APP_NAME=dev-syncday-api
        DOCKER_FILE=Dockerfile.dev
      fi

.upload-container-repository: &upload-container-repository
  <<: *resolve-submodule
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - lint
    - test
  services:
    - docker:dind
  before_script:
    - !reference [.resolve-variables-by-env, before_script]
    - |
      apt-get update && apt-get install -y git
      # Install Docker
      curl -fsSL https://get.docker.com -o get-docker.sh
      sh get-docker.sh
      # Install AWS CLI
      apt-get install -y awscli
      aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL
    - !reference [.resolve-core, before_script]
  script: |
    curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    cp ./.secure_files/.env.production ./.env.production
    cp ./.secure_files/.env.staging ./.env.staging
    docker build -t $APP_NAME -f $DOCKER_FILE .
    docker tag $APP_NAME:latest $ECR_REPOSITORY_URL/$APP_NAME:latest
    docker push $ECR_REPOSITORY_URL/$APP_NAME:latest
    docker logout

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

init:
  stage: .pre
  script: |
    if [ $CI_COMMIT_BRANCH == "main" ]; then
      EMV=production
      CI_ENVIRONMENT_NAME=production
      APP_NAME=syncday-api
      DOCKER_FILE=Dockerfile
    elif [ $CI_COMMIT_TAG != null ]; then
      EMV=staging
      CI_ENVIRONMENT_NAME=staging
      APP_NAME=stg-syncday-api
      DOCKER_FILE=Dockerfile.stg
    else
      EMV=development
      CI_ENVIRONMENT_NAME=development
      APP_NAME=dev-syncday-api
      DOCKER_FILE=Dockerfile.dev
    fi

    echo "DYNAMIC_ENVIRONMENT_NAME=$EMV" >> deploy.env    # Add the value to a dotenv file.

    npm install
  artifacts:
    reports:
      dotenv: deploy.env
  only:
    - main
    - tags # for staging
    - develop

build:
  <<: *resolve-submodule
  stage: build
  image: node:19-alpine
  needs:
    - init
  script: |
    npm run build
  artifacts:
    when: on_success
    paths:
      - dist/
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG != null || $CI_COMMIT_BRANCH == "develop"'

lint:
  <<: *resolve-submodule
  stage: lint
  needs:
    - build
  script: |
    npm run lint
  only:
    - main
    - tags # for staging
    - develop

test:
  <<: *resolve-submodule
  stage: test
  needs:
    - build
  script: |
    npm run test:ci
  only:
    - main
    - tags # for staging
    - develop
  artifacts:
    when: always
    paths:
      - coverage/junit-report.xml
    reports:
      junit: coverage/junit-report.xml

build-docs-with-coverage:
  <<: *resolve-submodule
  stage: deploy
  needs:
    - lint
    - test
  script: |
    npm i -D @compodoc/compodoc
    npm i -D nyc
    npm run test:coverage
    if [ "$ENV" = "production" ]; then
      npm run build:docs
    fi
  only:
    - main
    - tags # for staging
    - develop

deploy-docs-to-s3:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  needs:
    - build-docs-with-coverage
  script: |
    aws s3 sync ./docs s3://$S3_BUCKET --delete --acl public-read
  variables:
    S3_BUCKET: "docs.sync.day"
  only:
    - main

upload-staging-container-repository:
  stage: deploy
  environment: staging
  <<: *upload-container-repository
  script: |
    echo "Deploy to $ENV"
  only:
    - tags # for staging

upload-production-container-repository:
  stage: deploy
  environment: production
  <<: *upload-container-repository
  only:
    - main

deploy-to-staging:
  stage: deploy
  environment: staging
  dependencies:
    - upload-staging-container-repository
  needs:
    - upload-staging-container-repository
  only:
    - tags
include:
  - template: AWS/Deploy-ECS.gitlab-ci.yml
    rules:
      - if: '$CI_COMMIT_TAG != null'

deploy-to-production:
  stage: deploy
  environment: production
  dependencies:
    - upload-production-container-repository
  needs:
    - upload-production-container-repository
  only:
    - main
include:
  - template: AWS/Deploy-ECS.gitlab-ci.yml
    rules:
      - if: '$CI_COMMIT_BRANCH == "main"'

deploy-to-development:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  environment: development
  dependencies:
    - lint
    - test
  before_script:
    - apt-get update -y && apt-get -y install openssh-server
    - curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
    - dpkg -i session-manager-plugin.deb
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash  #download secure files(https://docs.gitlab.com/ee/ci/secure_files/index.html)
  script:
    # SSH over Session Manager
    - mkdir $HOME/.ssh
    - echo -e "host i-* mi-*\n
          ProxyCommand sh -c \"aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'\"" > $HOME/.ssh/config
    - cp ./.secure_files/syncday.pem ./syncday.pem && chmod 400 syncday.pem
    - cp ./.secure_files/.env.dev ./.env.dev
    - bash ./scripts/deploy-to-dev.sh $DEV_EC2_INSTANCE_ID
  only:
    - develop
