default:
  image: node:19-alpine

cache:
  paths:
    - node_modules/
    - dist/

stages:
  - .pre
  - build
  - lint
  - test
  - security
  - deploy
  # for ecs template
  - review
  - dast
  - production
  - cleanup

variables:
  APP_NAME: syncday-api
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

init:
  stage: .pre
  script:
    - npm install
  only:
    - main
    - develop

build-production:
  stage: build
  needs:
    - init
  script:
    - npm run build
  artifacts:
    when: on_success
    paths:
      - dist/
    expire_in: 1 week
  only:
    - main
    - develop

lint:
  stage: test
  needs:
    - build-production
  script:
    - npm run lint
  only:
    - main
    - develop

test:
  stage: test
  needs:
    - build-production
  script:
    - npm run test
  only:
    - main
    - develop

upload-container-repository:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  needs:
    - lint
    - test
  services:
    - docker:dind
  environment:
    name: production
  before_script: |
    amazon-linux-extras install docker
    aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REPOSITORY_URL
  script: |
    echo "Upload container image to AWS ECR repository"
    cat $DOTENV > .env.production
    docker build -t $APP_NAME .
    docker tag $APP_NAME:latest $ECR_REPOSITORY_URL/$APP_NAME:latest
    docker push $ECR_REPOSITORY_URL/$APP_NAME:latest
  after_script:
    - docker logout
  only:
    - main

deploy-to-production:
  stage: deploy
  dependencies:
    - lint
    - test
    - upload-container-repository
  environment:
    name: production
    url: https://api.sync.day
  only:
    - main
  script:
    - echo "Deploy to production"
include:
  - template: AWS/Deploy-ECS.gitlab-ci.yml
    rules:
      - if: $CI_COMMIT_BRANCH == "main"

deploy-to-development:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  environment: development
  before_script:
    - apt-get update -y && apt-get -y install openssh-server
    - curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
    - dpkg -i session-manager-plugin.deb
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash  #download secure files(https://docs.gitlab.com/ee/ci/secure_files/index.html)
  script:
    # SSH over Session Manager
    - mkdir $HOME/.ssh
    - echo -e "host i-* mi-*\n
          ProxyCommand sh -c \"aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p'\"" > $HOME/.ssh/config
    - cp ./.secure_files/syncday.pem ./syncday.pem && chmod 400 syncday.pem
    - cp ./.secure_files/.env.dev ./.env.dev
    - bash ./scripts/deploy-to-dev.sh $DEV_EC2_INSTANCE_ID
  only:
    - develop
