FROM keymetrics/pm2:18-alpine

WORKDIR /opt/syncday-api

RUN apk add --no-cache tzdata curl

ENV ENV production

COPY . .

RUN npm install --ignore-scripts

RUN npm run build

HEALTHCHECK CMD curl localhost:3011/ || exit 1
