export enum RedisStores {
    USERS = 'users',
    TOKENS_USERS = 'tokens:users',
    TEAMS = 'teams',
    VERIFICATIONS_EMAIL = 'verifications:email',
    VERIFICATIONS_PHONE = 'verifications:phone',
    WORKSPACES = 'workspaces',
    TEMPORARY_USER = 'temporary:users',
    EVENT_LINK = 'event-link',
    EVENT_DETAIL = 'event-detail',
    EVENT_SETTING = 'event-setting',
    AVAILABILITY = 'availability',
    HOST_QUESTIONS = 'host-questions',
    NOTIFICATION_INFO = 'notifications',
    SCHEDULES = 'schedules',
    GOOGLE_INTEGRATIONS = 'integrations:google',
    GOOGLE_CALENDARS = 'calendars',
    CALENDAR_SUBSCRIPTION = 'calendars-subscription',
    PG_PAYMENTS = 'pg-payments',
    INVITED_NEW_MEMBER = 'invited-new-member',
    TEAM_INVITATIONS = 'team-invitations',
    EVENT_TYPE_GROUP_SETTING = 'event-type-group-setting',
    MEMBER_COUNT = 'member-count'
}
